### ISSUE TITLE
couldn't deploy to heroku

### ISSUE THREAD

**Issue by anthonyjohnhinay** [karyeet/Mandarine#50]
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by karyeet** [comment]
It is very peculiar that you've gotten that message.
You'll have to provide the steps you took as I was able to successfully deploy on [heroku](https://mandarine-music.herokuapp.com/)

That being said, I've added better support for heroku (and like services)
- bind to env.PORT if available
- added engines to package.json

Furthermore, when you get past this issue I've noticed youtube gives a lot of 429 (rate limits) when hosting on heroku, so you may have to [configure play-dl with a cookie](https://github.com/play-dl/play-dl/tree/7eebccb41765b98df1528c64171e2d8510885036/instructions)
