### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by yeahIamblonde** [karyeet/Mandarine#51]
Guys, just installed this as I have asked to create a discord music bot. All seems to work well, except that I have no sound?? Any ideas? No errors. Just no sound. Probably some dumb mistake of mine?

**Comment by karyeet** [comment]
Hey, 
Please answer some questions so we can pinpoint the issue

- Where are you deploying the bot to? (ex. personal device, heroku, replit...)
- What version of node is installed? (can be checked with `node -v`)
- Does `npm install` run without issues?
- What architecture is the device? (arm/amd, 32/64)
- What commands did you run? (include arguments please)
- Does the bot have permission to speak in the voice channel?
- Does the issue persist when the bot has administrator privileges?

**Comment by yeahIamblonde** [comment]
1) Deploying at the moment on my local machine
2) Node version is 16.13.2
3) Yes npm install runs without issues
4) Running on linux mint on intel i5
5) Join (works) Play (works, finds a song but no sound)
6) yes
7) yes given bot admin

**Comment by karyeet** [comment]
Unfortunately I am unable to reproduce the issue on an i5 (x64) Linux Mint VM.

Make sure:
- Your system is updated with `sudo apt update` then `sudo apt upgrade`
- You are using the latest version of Mandarine, downloaded using the "Download Zip" button on the home page (not releases).
- You have enabled all intents on the Discord Developer Dashboard as I have recently noted in deploy section of the readme

and while it is unlikely, double check:
- Your system is not muted
- You can hear sound from other discord users in a voice channel
- The bot is not muted and its volume is not too low

To help narrow this down, try using the `>music` command to play from soundcloud. 
Ex. `>music charmander`
